### ISSUE TITLE
Final COLP edits

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#65]
- [x] reinstate ownership field #66 
- [x] Make field names all caps (i.e. TYPE) #67 
- [x] `expandcatdesc` add as field to COLP with values for `expandcat` values (like usetype) #68 
- [x] add lat/ long fields #69 
- [x] schema changes to match PLUTO #70 
- make bbl, billbbl double field
- make lat/ long fields and xcoords and ycoords double
- block and lot, cd are numeric
